### ISSUE TITLE
Node 2 cannot continue to participate in the PAXOS transaction after CRIU dumping

### ISSUE THREAD

**Issue by bluecloudmatrix** [milannic/libevent_paxos#12]
Using mongoose server, on my laptop.

 [start the three mongoose servers and the three nodes ---> sleep 5 ---> client1: ab -n 100 -c 1 ---> CRIU dumps the server.out(i.e. proxy-consensus process) of Node 2 ---> kill -SIGCONT the server.out of Node 2(after dump CRIU will make the server.out stopped, so we should wake it up by hand) ---> client2: ab -n 100 -c 1 ---> sleep 5 ---> kill all, the end].

From the logs of Node 2, we could find that it didn't receive and handle requests after dump. And if you add 'sleep 5' after above 'kill -SIGCONT', Node 2 will report:
1425565861.252845:Node 2 Haven't Heard From The Leader
1425565861.252908:Node 2 Lost Connection With The Leader
1425565861.252923:Node 2 Will Start A Leader Election

**Comment by ruigulala** [comment]
Hi Qiushan,
What does it mean by CRIU dumps server.out? Does it mean by CRIU records the states and other related info of server.out?

**Comment by bluecloudmatrix** [comment]
The CRIU dumping == checkpoint the process of libevent_paxos. Yes, CRIU will record all states and related info of the process.

**Comment by ruigulala** [comment]
OK. So does it mean that CRIU will suspend(or freeze) the current network activity in order to checkpoint? Thus, node 2 will no longer be able to receive packages?

**Comment by bluecloudmatrix** [comment]
Yes, node 2 will lose contact with the other two nodes.

**Comment by ruigulala** [comment]
I see. Here is what I think about the process. Checkpointing will make the node unavailable for a small amount of time. And the checkpointed node will initialize leader election. But since there won't be any responses to the leader election messages, it won't proceed. Meanwhile, the whole system can still proceed since there are still two nodes available. After check pointing, node 2 will receive ping message from leader again and the leader election process will be canceled. Everything back to normal.

**Comment by bluecloudmatrix** [comment]
Solved! Thanks very much, Rui:) What you said is reasonable and right. There are two reasons why Node 2 cannot continue to participate in the PAXOS transaction after dumping:
1) just like what you said, when I use kill -SIGCONT ${pid} to wake it up, Node 2 will initialize leader election. Because I haven't merged the leader election part into my current branch, Node 2 couldn't work normally, so that it also will not receive ping message from leader again.
2) The second reason is I should not use 'kill -SIGCONT ${pid}', because after it, the process is not waken up due to the lost of the signal. 

Considering the performance, I choose the second one. So I use 'killall -SIGCONT server.out' instead of 'kill -SIGCONT ${pid}'. killall can make sure the signal work, and after it, the process is waken up indeed. Node 2 can continue to work normally. Here is the performance data:

Concensus Time====Overall(1759):
    mean:747.597441204 us
    std:314.867552759

Response Time====Overall(1759):
    mean:899.862470513 us
    std:336.545204809

# 

Throughput (from ab log):
    324.433333333 req/s

# 

By contrast, if we don't use CRIU to do checkpoint work, the performance is:

Concensus Time====Overall(1751):
    mean:743.307296648 us
    std:311.943710973

Response Time====Overall(1751):
    mean:896.568232982 us
    std:348.267212087

# 

Throughput (from ab log):
    332.586666667 req/s

#

**Comment by ruigulala** [comment]
Great!!
Test the code with leader election. Let me know if it works or not. :)
Btw, How long will the node be freezed when doing checkpoint? Currently, the threshold for starting a leader election process is 8 secs. My concern is that would it be too long for CRIU to freeze the network?

**Comment by bluecloudmatrix** [comment]
Rest assured. Very quickly, in a flash.
