### ISSUE TITLE
Segfault right after running server.out

### ISSUE THREAD

**Issue by ruigulala** [milannic/libevent_paxos#2]
For the new code branch with leader election, the program segfaults right after being run.
Settings:
1. Using nodes.cfg with group_size set to 1.

**Comment by milannic** [comment]
Hi Rui:

I just arrived at US, after some settlement issues, I will look into this
soon, and you can also open all the debug info options to check the detail
of segfault, then you can give me a more specific report(eg. in which func).

Thanks.
Cheng

On Fri, Feb 13, 2015 at 3:50 PM, Rui Gu notifications@github.com wrote:

> For the new code branch with leader election, the program segfaults right
> after being run.
> Settings:
> 1. Using nodes.cfg with group_size set to 1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/milannic/libevent_paxos/issues/2.

## 

_Cheng Liu_

Candidate For The Master Of Computer Science In December 2014
Department Of Computer Science
Columbia University In The City Of New York, United States 10025
+1(347)-409-3268

**Comment by ruigulala** [comment]
Hi Cheng,
Thank you for replying.
Take you time. I don't think this is a complex bug to fix.
In order to fully understand the current code, I'll try to fix this by 
myself.
I'll let you know when I have any problems. :)

Rui

**Comment by ruigulala** [comment]
Hi Cheng,
The following is the stack trace. You can take a look when you have time.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ba175b in event_del () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
(gdb) frame
#0  0x00007ffff7ba175b in event_del () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
(gdb) w
Ambiguous command "w": watch, wh, whatis, where, while, while-stepping, winheight, ws.
(gdb) where
#0  0x00007ffff7ba175b in event_del () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#1  0x0000000000403453 in initialize_leader_ping (my_node=0x63d740) at ../src/replica-sys/replica.c:276
#2  0x0000000000409220 in initialize_node (my_node=0x63d740, log_path=0x414be7 ".", deliver_mode=0, user_cb=0x40c1a8 <update_state>, db_ptr=0x0, arg=0x637550) at ../src/replica-sys/replica.c:1391
#3  0x00000000004096f8 in system_initialize (node_id=0, start_mode=0x7fffffffec13 "s", config_path=0x7fffffffec18 "nodes.local.cfg", log_path=0x414be7 ".", deliver_mode=0, user_cb=0x40c1a8 <update_state>, 
    db_ptr=0x0, arg=0x637550) at ../src/replica-sys/replica.c:1495
#4  0x000000000040f2d5 in proxy_init (node_id=0, start_mode=0x7fffffffec13 "s", config_path=0x7fffffffec18 "nodes.local.cfg", log_path=0x414be7 ".", fake_mode=0) at ../src/proxy/proxy.c:730
#5  0x00000000004136b2 in main (argc=8, argv=0x7fffffffe928) at ../src/main.c:101
